enum ErrorEnum {
  DEFAULT = "DEFAULT",
  INVALID_CODE = "INVALID_CODE",
  USER_IS_NOT_FRIEND = "USER_IS_NOT_FRIEND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST",
  LIMIT_REACHED_TRY_LATER = "LIMIT_REACHED_TRY_LATER",
  USER_DEACTIVATED_OR_CANCELLED = "USER_DEACTIVATED_OR_CANCELLED",
}

export default ErrorEnum