enum ErrorEnum {
  DEFAULT = "DEFAULT",
  INVALID_CODE = "INVALID_CODE",
  USER_IS_NOT_FRIEND = "USER_IS_NOT_FRIEND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST",
  LIMIT_REACHED_TRY_LATER = "LIMIT_REACHED_TRY_LATER",
  FILE_VALIDATION_SIZE_ERROR = "Validation failed (expected size is less than 2097152)",
  USER_DEACTIVATED_OR_CANCELLED = "USER_DEACTIVATED_OR_CANCELLED",
  UPLOAD_EITHER_VIDEOS_OR_IMAGES = "UPLOAD_EITHER_VIDEOS_OR_IMAGES",
}

export default ErrorEnum;
