export const CHATS_GET = "CHATS_GET";
export const CHAT_CREATE = "CHAT_CREATE";
export const CHAT_ACTIVE_GET = "CHAT_ACTIVE_GET";
export const SEND_CHAT_MESSAGE = "SEND_CHAT_MESSAGE";
export const CHAT_MESSAGES_GET = "CHAT_MESSAGES_GET";
export const CHAT_SWITCH_ACTIVE = "CHAT_SWITCH_ACTIVE";
