export const USER_VALIDATE = "USER_VALIDATE";
export const USER_REGISTER = "USER_REGISTER";
export const USER_VERIFY_EMAIL = "USER_VERIFY_EMAIL";
export const USER_GET_BY_EMAIL = "USER_GET_BY_EMAIL";
export const OAUTH_UPSERT_USER = "OAUTH_UPSERT_USER";
export const USER_RESET_PASSWORD = "USER_RESET_PASSWORD";
export const USER_FORGOT_PASSWORD = "USER_FORGOT_PASSWORD";
